services:
  backend:
    image: ghcr.io/__IMAGE_OWNER__/poke-atlas-backend:__BACKEND_IMAGE_TAG__
    restart: unless-stopped
    expose: ["8080"]
  
  frontend:
    image: ghcr.io/__IMAGE_OWNER__/poke-atlas-frontend:__FRONTEND_IMAGE_TAG__
    restart: unless-stopped
    ports: 
      - "3001:3000"
    environment:
      API_ADDRESS: backend:8080